#!/usr/bin/expect -f
set timeout 30
set host [lindex $argv 0]
set user [lindex $argv 1]
set pass [lindex $argv 2]
set cmd [lindex $argv 3]

spawn ssh -o StrictHostKeyChecking=no $user@$host $cmd
expect {
    "password:" {
        send "$pass\r"
        exp_continue
    }
    "Password:" {
        send "$pass\r"
        exp_continue
    }
    "yes/no" {
        send "yes\r"
        exp_continue
    }
    eof { exit 0 }
    timeout { exit 1 }
}
expect eof
